# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally,
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
git:
  depth: 100

language: generic

os:
  - linux 
  
arch:
  - arm64 

dist: xenial

notifications:
  email:
    on_failure: change # [always|never|change] default: always

env:
  global:
    - PYENV_VERSION=3.7
    - PKG_TEST_PYTHON="--test-python=py37 --test-python=py27"
    - CHANS_DEV="-c pyviz/label/dev -c bokeh -c conda-forge"
    - CHANS="-c pyviz"
    - MPLBACKEND="Agg"
    - PYTHON_VERSION=3.7

stages:
  - test
  - name: extra_tests
    if: type = cron
  - name: conda_dev_package
    if: tag =~ ^v(\d+|\.)+([a-z]|rc)\d+$
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)+([a-z]|rc)\d+$
  - name: conda_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: docs
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: gallery
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: docs_dev
    if: tag =~ ^v(\d+|\.)+([a-z]|rc)\d+$
  - name: gallery_dev
    if: tag =~ ^v(\d+|\.)+([a-z]|rc)\d+$
  - name: docs_daily
    if: ((type = cron) OR ((commit_message =~ /\[doc-build\]/) and branch = master))
  - name: gallery_daily
    if: ((type = cron) OR ((commit_message =~ /\[doc-build\]/) and branch = master))

jobs:
  include:
    ########## Test Stage ##########

    - &default
      stage: test
      env: DESC="Python 3.6 tests" HV_REQUIREMENTS="unit_tests" PYTHON_VERSION=3.6
      before_install:
        - pip install flake8
        - which flake8
        - pip install pyctdev
        - wget -q "https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh" -O miniconda.sh
        - chmod +x miniconda.sh
        - ./miniconda.sh -b -p $HOME/miniconda
        - chown -R 1000:1000 /home/travis/
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - doit ecosystem_setup
      install:
        - conda create -n test-environment python=$PYTHON_VERSION
        - source activate test-environment
        - sudo apt-get -y install libjpeg-dev zlib1g-dev
        - conda install conda
        - conda install -c conda-forge ca-certificates
        - pip install "pyctdev>=0.5" "certifi==2019.11.28" "pip==19.3.1" "setuptools==42.0.2" "wheel==0.33.6" doit
        - conda install "zlib==1.2.11" "libstdcxx-ng==7.3.0" "readline==8.0" "sqlite==3.30.1" "libffi==3.2.1" "wheel==0.33.6" "pip==19.3.1" "libgcc-ng==7.3.0" "certifi==2019.11.28" "tk==8.6.10" "xz==5.2.4" "openssl==1.1.1d" "python==3.6.7" "ncurses==6.1" "setuptools==44.0.0"
        - pip install phantomjs tox pytest
        - conda install param>=1.7.0 pyct>=0.4.4 setuptools>=30.3.0 pyct-core holoviews numpy coverage
        - python setup.py develop
        - doit env_capture
      script:
        - pytest
        - nosetests
      after_success:  coveralls
      after_failure: sleep 10

    - <<: *default
      env: DESC="Python 2.7 tests" PYTHON_VERSION=2.7 HV_REQUIREMENTS="unit_tests"

    - &basic_deps
      <<: *default
      stage: extra_tests
      env: DESC="Basic dependencies" HV_REQUIREMENTS="basic_tests"
      after_success: echo "Success"
      script:
        - doit test_unit

    ########## DOCS ##########

    - &doc_build
      <<: *default
      stage: docs_dev
      env: DESC="docs" HV_DOC_GALLERY="false" HV_DOC_REF_GALLERY="true" HV_REQUIREMENTS="doc" PANEL_EMBED="true" PANEL_EMBED_JSON="true" PANEL_EMBED_JSON_PREFIX="json"
      script:
        - conda install $CHANS_DEV firefox geckodriver 
        - bokeh sampledata
        - nbsite generate-rst --org pyviz --project-name holoviews --skip ^reference
        - python ./doc/generate_modules.py holoviews -d ./doc/reference_manual -n holoviews -e tests
        - nbsite build --what=html --output=builtdocs
      after_success:
        - aws s3 sync --quiet ./ s3://holoviews-doc-builds/$TRAVIS_BUILD_NUMBER --exclude=".git/*" --exclude="doc/nbpublisher/*"

    - &gallery_build
      <<: *doc_build
      stage: gallery_dev
      env: DESC="gallery" HV_DOC_GALLERY="true" HV_DOC_REF_GALLERY="false" BUCKET="dev." HV_REQUIREMENTS="doc" PANEL_EMBED="true" PANEL_EMBED_JSON="true" PANEL_EMBED_JSON_PREFIX="json"
      script:
        - conda install $CHANS_DEV firefox geckodriver
        - bokeh sampledata
        - aws s3 sync --quiet s3://holoviews-doc-builds/$TRAVIS_BUILD_NUMBER ./
        - git reset --hard --recurse-submodule
        - nbsite build --what=html --output=builtdocs
      after_success:
        - aws s3 sync --quiet ./builtdocs s3://${BUCKET}holoviews.org/
        - aws s3 rm --recursive --quiet s3://holoviews-doc-builds/$TRAVIS_BUILD_NUMBER

    - <<: *doc_build
      stage: docs_daily

    - <<: *gallery_build
      stage: gallery_daily
      env: DESC="gallery" HV_DOC_GALLERY="true" HV_DOC_REF_GALLERY="false" BUCKET="build." HV_REQUIREMENTS="doc" PANEL_EMBED="true" PANEL_EMBED_JSON="true" PANEL_EMBED_JSON_PREFIX="json"

    - <<: *doc_build
      stage: docs

    - <<: *gallery_build
      stage: gallery
      env: DESC="gallery" HV_DOC_GALLERY="true" HV_DOC_REF_GALLERY="false" HV_REQUIREMENTS="doc" PANEL_EMBED="true" PANEL_EMBED_JSON="true" PANEL_EMBED_JSON_PREFIX="json"
      after_success:
        - aws s3 sync ./builtdocs s3://holoviews.org/

    ########## END-USER PACKAGES ##########

    ### CONDA ####

    - &conda_pkg
      <<: *default
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID CHANS_DEV="-c pyviz/label/dev -c bokeh/label/dev"
      install:
        - doit package_build $CHANS_DEV $PKG_TEST_PYTHON --test-group=unit
      script:
        - doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev

    - <<: *conda_pkg
      stage: conda_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID CHANS="-c pyviz -c bokeh"
      install:
        - doit package_build $CHANS $PKG_TEST_PYTHON --test-group=unit
      script:
        - doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev --label=main

    ### PyPI ###

    - &pip_pkg
      <<: *default
      stage: pip_dev_package
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - travis_wait 30 doit develop_install $CHANS_DEV -o unit_tests && pip uninstall -y holoviews
        - doit pip_on_conda
        - doit ecosystem=pip package_build
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}

    - <<: *pip_pkg
      stage: pip_package
      env: PYPI="https://upload.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - travis_wait 30 doit develop_install $CHANS_DEV -o unit_tests && pip uninstall -y holoviews
        - doit pip_on_conda
        - doit ecosystem=pip package_build
      script: doit ecosystem=pip package_upload -u $PPU -p $PPP -r ${PYPI}
